//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyCaLam
    {
        public int MaDangKyCaLam { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayDuocDangKy { get; set; }
        public Nullable<int> STTCaYeuCau { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
    }
}
