//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemVaThuong
    {
        public int MaDiemVaThuong { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> Diem { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> GameTetris { get; set; }
        public Nullable<int> GameQuiz { get; set; }
        public Nullable<int> GameMineSweeper { get; set; }
    }
}
