//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoreWeekReward
    {
        public int MaPhanThuong { get; set; }
        public Nullable<int> DiemCanDeDoi { get; set; }
    }
}
