//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanLiCaLam
    {
        public int IDCa { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
        public Nullable<int> STTCa { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
        public Nullable<System.TimeSpan> GioBatDau { get; set; }
    }
}
