//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiThuVienUeh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int IDThongBao { get; set; }
        public string TieuDe { get; set; }
        public Nullable<int> IDNguoiGui { get; set; }
        public string NguoiGui { get; set; }
        public Nullable<int> IDNguoiNhan { get; set; }
        public string EmailNguoiNhan { get; set; }
        public string ChucVuNguoiNhan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    }
}
